apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ginnyvt
  namespace: ginny-prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ginny-infra
    namespace: ginny-prod
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: it@harrytang.xyz
        name: mrgitops
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: main
  update:
    path: ./apps/production
    strategy: Setters
