---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: headless
  namespace: harrytang-prod
spec:
  imageRepositoryRef:
    name: headless
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web
  namespace: harrytang-prod
spec:
  imageRepositoryRef:
    name: web
  policy:
    semver:
      range: '>=1.0.0'
