apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
  namespace: harrytang-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-depl
  template:
    metadata:
      labels:
        app: web-depl
    spec:
      volumes:
        - name: next-build
          emptyDir: {}
      initContainers:
        - name: next-build
          image: ghcr.io/harrytang/web:main-b0cb998-1714896214 # {"$imagepolicy": "harrytang-staging:web"}
          command: ['sh', '-c', 'cp -r /app/.next /app/.build']
          imagePullPolicy: Always
          volumeMounts:
            - name: next-build
              mountPath: /app/.build
      containers:
        - name: web
          image: ghcr.io/harrytang/web:main-b0cb998-1714896214 # {"$imagepolicy": "harrytang-staging:web"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: web-env
            - secretRef:
                name: web-env
          volumeMounts:
            - name: next-build
              mountPath: /app/.next
