apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
  namespace: harrytang-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-depl
  template:
    metadata:
      labels:
        app: web-depl
    spec:
      containers:
        - name: web
          image: ghcr.io/harrytang/web:main-899e401-1714893139 # {"$imagepolicy": "harrytang-staging:web"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: web-env
            - secretRef:
                name: web-env
