---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: next-data-pvc
  namespace: harrytang-staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 1Gi
