---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-env
  namespace: ginny-staging
spec:
  encryptedData:
    REVALIDATE_TOKEN: AgBW7xKd257YSlsoKr9QQ+4dcFseVVab4q20RKkuucgfPsuBHKQFiLf+k6rutJtmdcH5qe1gYe4LRDOYGjE6V6wBOopxrvU3f4vsGFev79vCGEEwjQR5yYKSDLHG2xMdgdn80Lb1KoW+mQ/QGEWI3MTE356PuA8JBfIVQ323eRq/668EvWzP63MzQeqznr56vc7ewqdHHK/3gVfy/vwPyE6p5Tr/JzWeHRoQjkTzQuHmOToj4Vz+5fHRpJs+2NKD/ysWHfcqGX2q0vCfBwfwALNqdIPkE1Vl/Tyyus8u3gPmFzM6XH9khDvKYRxNli9RbL00h+pvALDQSO9uGqO2+uZI4CqjuQBu+OODORk5oCsVptKkYLLo9zHlh+wuxSrCYGCwFDrDJ3P8oGDdz5vNDmI/jaMgTVkavckpNWYpxuZz0UsJFT5TOu04ZOMW1GJ1ybT+Q/mk+5zi5qU1ToJubVc+AuJ3js05qdCi7OU7ToWrItoGt+rq8d6FE0Dsi0a8z4IrWVyuI0y5EVlIkot146WLZuGRV5wcyyFutJ03OpTm1s/5HkcPc2/AMtrVw200p2v0pES+UJy0Jqmivpukhl1ZRomvN3HUCyXRwSKh7geM7c5YW18wPh+fQOJpAxMEyUAI4xt/iAakph/9IjBBj75aWFIedT4OUO643A8vn8fJhiGz1HeIT0vh5sU3SZ8oAO7E1FT4oeVR3Eu3r5zuifTzj9r67rnVajikPspZNJN/uqysMhUM2ThD5gGmPA==
  template:
    metadata:
      creationTimestamp: null
      name: web-env
      namespace: ginny-staging
