---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-env
  namespace: harrytang-staging
spec:
  encryptedData:
    REVALIDATE_TOKEN: AgAoucVEuLXlKD69PJ/5Fgp7MduwBfBoiveC4rGKrJ4Hk3UwAyHP32Y4ZSH34ZZb3BtsdhkMQQvDStSd4zoaeAQy9RsNzAwWTBfKjtNO+CFfMNvag0mfx8qP7h2V8yNCA9o1l3IBn4K/iR7MLKAUeKD2a+vJTmDD9gaAtBbl0fAEjZaQaevGHMjeNRc/H4Ec+hYoOKh+U6yZPnZK8VQopwJQriCX0NlNvqecJ/CbWTkIpOZAwB99JwZNFAdoSsJhFuvB8f/yO46osFlIYbQLpYVl6GgOIS4CihLcORiQot5zY9WJZwJLETZM//4KyLzpzb7lwpyprwV1E6d13OG5otUI57zoxVogsXLOn+CaEdYGo1nf+S59mgzdOZlcKf/z3ioM/Q+9MhhkrFUanDUX9TQqnxBoEoy76Mx8+rbG/cixL6B26CJiFASY6rZCHmx2O2WHwlMvZ+v66E6QZ4PoOjIC71Dhbo2ibpwzgeOBlaKAEJw2hKVVykGaKrrSd55OT72hTJXnJf5uEAGTv7ChHNUnE4L5HWywHg/FXgxBNrGuDy5r6WkTn/LmXx4sNyLT0afUFweD44JGEFXAx4dUJTj21I6xZeP6FA/f8tf/sma+ra8fEgaWAhh+pBqs91p42ZGm+Z6snieDEpvGmN09Gc8pE8cL+T5BVdJYhOozF3xuqhNlvSxQICl8g4w6DUScJNvF5LqPLwkvXtu5LvAE3ybs9ewiK9++BVPoHPG6zH6JY5aSCJeje1v5o8/7bQ==
  template:
    metadata:
      creationTimestamp: null
      name: web-env
      namespace: harrytang-staging
