apiVersion: v1
kind: ConfigMap
metadata:
  name: headless-env
  namespace: ginny-prod
data:
  # Strapi
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "1337"
  STRAPI_TELEMETRY_DISABLED: "true"
  STRAPI_ADMIN_BACKEND_URL: "https://cms.ginny.dev"
  # Database
  DATABASE_CLIENT: "mysql"
  DATABASE_HOST: "maxscale-galera.galera"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "ginny-prod-headless"
  DATABASE_USERNAME: "ginny-prod-headless"
  DATABASE_SSL: "false"
  # SMTP
  SMTP_HOST: "smtp.eu.mailgun.org"
  SMTP_PORT: "587"
  SMTP_USERNAME: "postmaster@app.ginny.dev"
  SMTP_FROM: "no-reply@ginny.dev"
  # STORAGE
  STORAGE_HOST: "assets.ginny.dev"
  STORAGE_ROOT_PATH: "prod"
  CF_ACCESS_KEY_ID: "b0bc37581f1906ca64fe1299472883cc"
  CF_ENDPOINT: "https://69d8ed804ba4e99d6a59c1bff745d2bf.r2.cloudflarestorage.com"
  CF_BUCKET: "headless-strapi"
