apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: web-runner-set
  namespace: harrytang-staging
spec:
  interval: 24h
  chart:
    spec:
      chart: gha-runner-scale-set
      version: '^0.9.2'
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-systems
      interval: 24h
  values:
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
    githubConfigUrl: https://github.com/harrytang/web
    githubConfigSecret: gh-token
---

