---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: harrytang-staging
spec:
  encryptedData:
    credentials.json: AgApSbxQlDb+Wihywg9MRQRmBu2Dk5y/HIITNXIpnlft7+LUukhIevhae7xhnU74MRRkbSsOJhMPi17V8UBs8z5r7FOEbZ1acenOGHNb7myM5nCYXuVxFHLUc6+b/VE/jwwFvT1U7tzSCJ2Iutnjee5lw0z0GPDqf92vg6EB/KW+m9Ctkjz0j4lJzENNQMQCiGvkiVJU+p84Ebse3e0VafsV0p6HLcSxZYNWy3BPR2AcRYjcSLKnL4+UGDGKOVMR0fNyaf5uqXR0UwA9eQGzLkqGs+d23U61ffDXH35ohkIiBETGRp8pKUAwj3tWwZKc1Geqp2q0PcNzdEgRaCWSZcTFU0c1cvaGARrB3lc/l+7l9NWDxEpTSuUpQHAoXoDsUAjYr+ArjwQ95hJVsKiaQg2ftAz97ELkNSIvmqBy0KdTjyX4ubUfxoPdyIRAidn8FLZ6qrL44S1jpZr/xA3urQLk+jOxjtbUBc3pcFCzYdEoHTqbzMDPFVxprOV77XppBthCcVKXmkVOmOxqhOBkftyYRMPsbW21DwUuOiU1BuEfNLjsIVXLA15a4hMxMDMByTiDxmKlzNRgREnCgsOwfdtRNjxjQquPOpXPdFoM8XZVv/MpGi6scrOJDrS/deW3naSJABFFMQIXS0upZRALDgXEJlqAeKYkkVE+M7KLLQfg1rznT06g/TZwmLxrOe2ycljrrIZfthE8XlbaWFlKT1CqJ5F2g3epU5tfbMHRjs7I1XCtbDOVGkdR/xMVBHj/WXkx0kcvCtiVq05YE79BNgwZ4OLbysOa5z2yuZoLIPEVZv+t/YpEDiCDDJjhfHkSoFJN8GmTlOxzIaiRUONEEEGR4EgiZYSPfO6yWmhEjpGChwbBn6ADqBQxfauiu1M5lAwrtALxGWm1xkQxZnT2M5i5UA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: harrytang-staging
