---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-env
  namespace: ginny-prod
spec:
  encryptedData:
    REVALIDATE_TOKEN: AgAcpDhf99Vk+cDWUA5DzSZILPXR8ibFEFPWt+6Vn97VwsgU8kwoluIbtnSK3wI2WJp0tmuH0XGhugfoYzWUYCNPg6jSPDPamA10/FuPQI4BV53JuRgVTcZ38E5WTDNrtcxKmhKhBSuMVOwgzZ/Z5cDnCrkdkyUq7BAYSQGSn9gz17sb3qgxJ8QOyhVP5p6ve2j8Ox2nSGUTLaQRmG+rYxMWjTr4/OFFcwEUj0/fC42z92qboeYZEABBGwzNfCREkRyYE3yOhmwD0IsWsb2uztfBfs6+hz9M7rS1PRpaZ/6f5kL9h289iF1s13m8EuTT4E1XoBILQvU2zIgeHV9RMelkcNDrS1rko4Yfj+jV3LKwDY7eOl+KaZi7PyUIkugtoWozuD+ZZVuAoXD1RY/k3vjP0fbugg3cRIYoB/cA0ufvQeQOdfR9rLmJ3Pj2ct5bKo1pfki/5MmtLwsgLc22KcyT0M5+I080Ge0PDcDDPKLMDekKnD3YqELJrjxLKLuXDZ1qA3w+f9CKrXyROOCNAVUHfkWcZ+dsYJuPKBzP5GS7nkvvOhxqQ7KTciMPxl+KsyZKatcdCNmOVQVSHV1rm7wJPwaXCqHkjS3sRFFVfHi/I5MLBxCZiAGu1uDDQXM7wj6thGPR0KWgg7MCROZRVW0R1jl73FQ1pETxZBLw8JIk5JLhl1kSHCfif0EjcV+iXXdjOwF4eEWBGeM6efxA/SizFz/ppHX9QgumKxGF28ZaGWm1cbtetVyUONen+w==
  template:
    metadata:
      name: web-env
      namespace: ginny-prod
