---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-env
  namespace: harrytang-prod
spec:
  encryptedData:
    CF_API_TOKEN: AgAf5O+ftckmhH+Jk2fhhX6xhxxaP5/O7oN3BjIvy8zEaTIw9+NAvOtwoIlk6Bgm+thz/SuHwjMkW+LWO6wx2l4K3PSk/P86S4l+dnEr0kZP+KV2Rc8M4sFl0pPrPRSegoYI4Il0CkdjvmBlwCV/U4Qd05fs4hHft3X5UQ2dgAUS3NpI+TUJ4EamY0RFAWCtdTCFmv3fker793uYRfzJQUM9hrl/IhlkK7iOsAFKpCPamQL93jm5Y/g2qcUYAhBO+wHwX4GJp40OR8LgRQytocSxSPjX46LJ/0wOPOtbGVGY6Q4sddikZgknfoxWZpxL1K57trh+KfyKQLuZhpJZM+B5248v4VmlHomfl0AiBlyySlvRmyNEeqSML+gdUD02yN80HY2x+GGYgjRa9tnQmB7wX4+mcW3UEVgR0waqigk7oUle7BzVkk4JeuIHnTkoP8jDi9gdfXVvX/TKkPmjeIRA4iki26q1mF0jnln6H331AHZURCLQABQOuiJDBFZpds1HL5VeFaOcXHUOB5KYmoZBtyURJl5q6j+8X0OXgwGCs9aKNzVgUsU2VgD/8B5rsDsI6dQcfv3Kke1GX4aSpU5rroHuz6oY5x5uMOJh/wOfwXguwbMf2DZYFy02LLSKErCJv3Wp30VtGsT6kjWM1i1BfRZ/ugBay7OUwIKP8zOu8bxXmSVSfHuNNuV7hrHfhckOb7JacYtbFsWjTxiQBD+8iCLjl4B3NU7Lwhm/G0BKGgZ2s0mVgYT2
    REVALIDATE_TOKEN: AgBHApU4KpnOAQWdA7E6ZoFKj15gyCUfpTQY9E0rNF1HVoZQqqdKVCS98JevUlKlQo/EBd6lA81L5tNO5o7fDFwYExI/EtX6QSEtJXGpqLwUoJlCx3G7SAfu6wOiJz4sPRECOu1LZ1LQe0NQ0vilxjRW8AEb4hO2GIB1HYLqJwY9xgD0yttvdCulEOaFlg9A7cJA7gE2WpjlYUCQOtiUGVr3tX95XeM1Be+wcN5tuYtEO8awPKC/3Y/idA1nTp5RhMr0wZ6Y5p4U6XnxuAJcrD6Q89FodqpTsSLs0kVBHKFsDdbCYIZ90H0XP3fNUZFaz7Qdx4jiFdzvJfs7IV0eTyQFqpol5B6JmtJxxChVoBi4VCXJAh70O9pWE+RhIb+wzlzXeMC4YzkKirC5JAYHpF9DbBd9jID3vBvMl4XeXmdzHP0rmMjzLLkKX3tQn3mGXrAxrKKL7IBb5J3OONKsMAWlw/NRZiSnQDJgh1XFwL6NBy/mdYBndSEKRyT32rGxcIATt2SwP0S13zkFMsH9V3/WEeaK9hgufdRkxxpkOCsT8DLu/4mKthE+RJvQmeJXXpDpRJfVnkLRViAzVRGMEvsBoaZVl5Ddhgea/a+6oWrJqykcqbHrKcmMWXr5DvUgRBjlZC3nWvA/UTZ5UFWmbahEcK7xyH/FAmwVFE1D6MVWqW6DG6vDQH1J9qy/FCOTRYEDjRuNqz01ywtHggxUt+3EpFUpxrCZ+mKleq5nfKM1kcmYkDtIGL0x+3xh9w==
  template:
    metadata:
      creationTimestamp: null
      name: web-env
      namespace: harrytang-prod
