apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: web-runner-set
  namespace: harrytang-staging
spec:
  interval: 24h
  chart:
    spec:
      chart: gha-runner-scale-set
      version: '^0.9.2'
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-systems
      interval: 24h
  values:
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
    githubConfigUrl: https://github.com/harrytang/web
    githubConfigSecret: gh-token
    template:
      spec:
        # initContainers:
        #   - name: kube-init
        #     image: ghcr.io/actions/actions-runner:latest
        #     command: ['sudo', 'chown', '-R', '1001:123', '/home/runner/_work']
        #     volumeMounts:
        #       - name: work
        #         mountPath: /home/runner/_work
        securityContext:
          fsGroup: 123
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ['/home/runner/run.sh']
---

