---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb
  namespace: ginny-prod
spec:
  encryptedData:
    password: AgA+7VPm/2S73ZwVKT/LNwtFSgynNa9zH0C/A+dpkLvt/n/0oHuVHMsbX0AJQS1/Fkt6P1BSjWb3MOW1CC5v+Cz+EXsMc/0Y+KD75oDk9RPzFGqHjhrirfitz/WZxDoF/08kLcAgNR09LXZPv9sQ9H2zkjsrkmGWZD9mD+Isa7RHnghgL7bfRkJ0NTNGspUxwiBq8T7bfpV1FWoSVSJhxh0XVk0NF8MdrQ6BsFzBDKSUHm4X627oWWGGDcUdK+FCgSqN+Gfa12pMP5IVMt/jJ3i6cTjjIO2Fo1v9tbgbJYrz8/jjs9tBaOqOEKwzw06FXrl+2URdfy8JfU/BCp5L/ZDKIt6f+zURu1KOE30FcIgILGjlvlXLmLV90Nlhq8i4h0jXeXeKTdGUpG3hmpdILnNNTOVIA5On8pVhhiNyI0Sa3qgMgs1pUnCAiFpslFuJdbaDJejHYFzlmIR4Rooo1DYwP1YKz7g+8arb/ErNvNEz8laSmtsg8SOhFy6ZOu9LppkzJeRydHCpsEEoAHg5Br9h3P0kVF05AfeW7yXUxBz2GkI8T3pYNB07s/dPh3OdWRgiGRGRVDXqyx95RYEYAUSW1KS9rUXDQvB9Q6EhoLovElcMimDmg5FTZ2HhDmKnLSOexfMyOZdEFhXuGjTTimF8kSFMxSHvdOPNP+QDkjfASG7AImkCswF/99FWxBU/6Brbg4ajdEt5MaMYDY0FdvCoW5uUNakVzf90ALA6gwoRtZ2CYmJh1vb7dvxmdA==
    root-password: AgBMC3JWR+3cJFiPH/rC3yoQrhYOjjOTuL5caf87LtGv737pVF/uwkQrkEbpKseVQgWBFrSL8AHU8XcveFwROle5O1EpYnPllVyH+TE85mKI7Xv6JPyyMqghptij1onAt3SkpNtTH+S7+vq5+7wVRCyQVQvaA1le0I+64dtgBwpYAhcBHRIX+VSMexgruR/7UTd5U0+ODaXMzbT4pABcXsZwOuqZ73qW8eORES+b46iQwq6ECsG6nTsIBK6KpAgc0lbUgJe2Ls7DDKfCUuEc4J5Sx94WGwMXqxwadc8mFLnM4ZKWP/yO+EzU1rcRe7QUl/K9ixW6baxiGcyImheAk4AErnBk8dpG9IiXw2B+K96305oPDpR9KDcL36EVeG843V1gRjuD1b3RCsoubUV33GSMSjq0XLajy5UnYEXZepj3A4oTGbzoS9H6mEIIdDKIQnh2gWJLJ8ySS2bLyb0cGfJzndlx6iwMh0b8EtoZhusp17ApHMr20rcRFWVBA5JXIqK+HNza67hCfM7pMsxAgBO5RQxg0HXyLaW6mnUJghjDd+3i2+LQsq9ktnrZCPJRGmmY2bcnCaIr73qJk6NCYqX9BY11Ogl09nS8fe6nUOtFGHdMrGhA2jP1yaZybl7W7Yz2x+y1Pvq0HJjrrb53eaO0B7wyjpG2alKeUx5R7ivNuu4Wjj5WEOw3n8CpJVHaD3yO+wwkiUtzNRw1r0AmFPMUbHuzpUkx+2L76EQf5tGFPa0r26bl0IHx1IaFMw==
  template:
    metadata:
      name: mariadb
      namespace: ginny-prod
